export const pdpData = [
  {
    id: 1,
    title: "Smart Watches / Fitness Bands",
    description:
      "Smart watches and fitness bands with bulk customization options make ideal corporate gifts. They combine health-focused functionality with sleek design, offering personalized branding and promoting wellness among clients or teams.",
    imageUrl: "/watch.jpg",
    url: "smart-watches",
    price: 945,
    originalPrice: 1499,
    bgColor: "#f0fdf4",
  },
  {
    id: 2,
    title: "Luxury Pen Sets",
    description:
      "Metal and plastic pens, great for bulk gifting or desk accessories. Options for laser engraving or full-color logo printing",
    imageUrl: "/pen.jpg",
    url: "luxury-pen-sets",
    price: 599,
    originalPrice: 899,
    bgColor: "#fff7ed",
  },
  {
    id: 3,
    title: "Branded Travel Kits",
    description:
      "Branded travel kits offer a practical and stylish gifting solution, featuring essential travel accessories in a compact design. Ideal for corporate giveaways, they enhance brand visibility on every journey.",
    imageUrl: "/bag.jpg",
    url: "/branded-travel-kits",
    price: 1250,
    originalPrice: 1799,
    bgColor: "#f0f9ff",
  },
  {
    id: 4,
    title: "Metal Table Clocks or Crystal Showpieces",
    description:
      "Metal and plastic pens, great for bulk gifting or desk accessories. Options for laser engraving or full-color logo printing.",
    imageUrl: "/bag.jpg",
    url: "/pdp-one.png",
    price: 799,
    originalPrice: 1099,
    bgColor: "#fef2f2",
  },
  {
    id: 5,
    title: "Customized Aromatherapycor Wellness Boxes",
    description:
      "Customized aromatherapy or wellness boxes provide a relaxing experience with curated items like essential oils, candles, and herbal teas. Perfect for employee appreciation or client gifts, personalized to reflect your brand.",
    imageUrl: "/admin.jpeg",
    url: "wellness-boxes",
    price: 1350,
    originalPrice: 1899,
    bgColor: "#fefce8",
  },
  {
    id: 6,
    title: "Premium Corporate Jackets / Blazers",
    description:
      "Metal and plastic pens, great for bulk gifting or desk accessories. Options for laser engraving or full-color logo printing",
    imageUrl: "/pdp-one.png",
    url: "corporate-jackets",
    price: 1899,
    originalPrice: 2499,
    bgColor: "#e0f2fe",
  },
  {
    id: 7,
    title: "Branded Gift Vouchers or Subscription Boxes",
    description:
      "Metal and plastic pens, great for bulk gifting or desk accessories. Options for laser engraving or full-color logo printing.",
    imageUrl: "/pdp-one.png",
    url: "gift-vouchers-subscription-boxes",
    price: 999,
    originalPrice: 1399,
    bgColor: "#f3f4f6",
  },
  {
    id: 8,
    title: "T-Shirt",
    description:
      "High-quality cotton and polyblend T-shirts ideal for staff uniforms, events, or promotional giveaways. Available in all sizes, colors, and customizable with screen printing or embroidery of logos.",
    imageUrl: "/t-shirt.jpg",
    url: "custom-tshirts",
    price: 499,
    originalPrice: 799,
    bgColor: "#fef9f9",
  },
  {
    id: 9,
    title: "Luxury Pen Sets",
    description:
      "Metal and plastic pens, great for bulk gifting or desk accessories. Options for laser engraving or full-color logo printing.",
    imageUrl: "/pen.jpg",
    url: "luxury-pen-sets-2",
    price: 749,
    originalPrice: 999,
    bgColor: "#fffbeb",
  },
  {
    id: 10,
    title: "Notebooks & Diaries",
    description:
      "Elegant office notebooks and weekly planners with flexible binding styles, available with custom-printed covers and company branding.",
    imageUrl: "/spiral-notebook.jpg",
    url: "notebooks-diaries",
    price: 399,
    originalPrice: 699,
    bgColor: "#f0fdf4",
  },
  {
    id: 11,
    title: "Eco-friendly Jute Bags or Cotton Totes",
    description:
      "Eco-friendly canvas totes or jute bags. Sturdy and spacious, ideal for events and office use. Fully customizable with logo and taglines.",
    imageUrl: "/jute-bag.jpeg",
    url: "eco-jute-bags",
    price: 299,
    originalPrice: 499,
    bgColor: "#ecfccb",
  },
  {
    id: 12,
    title: "Steel Water Bottles",
    description:
      "Leak-proof, BPA-free stainless steel bottles with a sleek finish. Ideal for eco-friendly branding. Custom laser engraving and printed logo options available.",
    imageUrl: "/pdp-one.png",
    url: "steel-water-bottles",
    price: 699,
    originalPrice: 999,
    bgColor: "#e0f2fe",
  },
  {
    id: 13,
    title: "Sippers or Coffee Mugs",
    description:
      "Customized sippers or coffee mugs are perfect for everyday use and brand promotion. With personalization options, they make functional, memorable gifts that keep your brand visible at home or the office.",
    imageUrl: "/pdp-one.png",
    url: "coffee-mugs",
    price: 399,
    originalPrice: 649,
    bgColor: "#fff1f2",
  },
  {
    id: 14,
    title: "Keychains",
    description:
      "Customized keychains are compact, practical gifts that keep your brand in hand every day. Ideal for corporate giveaways, they offer great visibility and can be tailored to match your branding style.",
    imageUrl: "/keychain.webp",
    url: "keychains",
    price: 99,
    originalPrice: 199,
    bgColor: "#fefce8",
  },
  {
    id: 15,
    title: "Basic Laptop Sleeves or File Folders",
    description:
      "Executive and budget-friendly diaries with hard/soft covers, PU leather finish, and ruled or planner formats. Customization includes logo embossing, inside page branding, and bookmarks.",
    imageUrl: "/pdp-one.png",
    url: "laptop-sleeves",
    price: 699,
    originalPrice: 1049,
    bgColor: "#f0fdf4",
  },
  {
    id: 16,
    title: "Cap/Hat with Embroidery or Print",
    description:
      "Branded baseball or snapback caps made from durable cotton fabric. Great for outdoor events and staff uniforms. Custom embroidery available.",
    imageUrl: "/cap.jpg",
    url: "custom-caps",
    price: 249,
    originalPrice: 449,
    bgColor: "#f0f9ff",
  },
  {
    id: 17,
    title: "High-end Bluetooth Speakers or Earbuds",
    description:
      "High-end Bluetooth speakers or earbuds customized with your brand offer a stylish, tech-savvy gifting solution. Perfect for corporate giveaways, they blend premium sound quality with impactful brand visibility",
    imageUrl: "/speaker.jpg",
    url: "bluetooth-speakers",
    price: 1899,
    originalPrice: 2499,
    bgColor: "#fef2f2",
  },
  {
    id: 18,
    title: "Premium Leather Diaries & Organizers",
    description:
      "Premium leather diaries and organizers with custom branding offer a sophisticated, practical gift choice. Ideal for professionals, they combine elegance and utility, reinforcing brand presence with every use.",
    imageUrl: "/notebook.webp",
    url: "leather-diaries",
    price: 850,
    originalPrice: 1199,
    bgColor: "#fff7ed",
  },
  {
    id: 19,
    title: "Customized Gift Hampers",
    description:
      "Customized gift hampers with gourmet snacks, dry fruits, and wine accessories make elegant, thoughtful presents—ideal for any occasion, blending taste, luxury, and personalization in a premium package.",
    imageUrl: "/pdp-one.png",
    url: "gift-hampers",
    price: 2250,
    originalPrice: 2999,
    bgColor: "#faf5ff",
  },
];
